### ISSUE TITLE
Program does not load upon opening

### ISSUE THREAD

**Issue by paul23612** [labo89/nusdm#8]
I have the correct key, downloaded .net, but it does not load.

**Comment by hexadezi** [comment]
What does the event log say?

**Comment by paul23612** [comment]
Hello Hex, thank you for your time.

There were 2:
Faulting application name: nusdm.exe, version: 1.1.0.0, time stamp: 0x63747414
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2913, time stamp: 0xa1c3e870
Exception code: 0xe0434352
Fault offset: 0x000000000002cf19
Faulting process id: 0x2474
Faulting application start time: 0x01d97ad8278875b6
Faulting application path: D:\nusdm-master\nusdm\nusdm\bin\Debug\netcoreapp3.1\nusdm.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 315be3ed-d3c0-4900-a66c-af32bf2a097a
Faulting package full name: 
Faulting package-relative application ID: 

Application: nusdm.exe
CoreCLR Version: 4.700.22.55902
.NET Core Version: 3.1.32
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Windows.Markup.XamlParseException: 'The invocation of the constructor on type 'nusdm.MainWindow' that matches the specified binding constraints threw an exception.' Line number '7' and line position '2'.
 ---> System.TypeInitializationException: The type initializer for 'nusdm.SettingsProvider' threw an exception.
 ---> System.Text.Json.JsonException: 'U' is an invalid escapable character within a JSON string. The string should be correctly escaped. Path: $.SavePath | LineNumber: 3 | BytePositionInLine: 18.
 ---> System.Text.Json.JsonReaderException: 'U' is an invalid escapable character within a JSON string. The string should be correctly escaped. LineNumber: 3 | BytePositionInLine: 18.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeStringAndValidate(ReadOnlySpan`1 data, Int32 idx)
   at System.Text.Json.Utf8JsonReader.ConsumeString()
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, JsonReaderException ex)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at nusdm.SettingsProvider.Load() in D:\nusdm-master\nusdm\nusdm\Services\SettingsProvider.cs:line 53
   at nusdm.SettingsProvider..cctor() in D:\nusdm-master\nusdm\nusdm\Services\SettingsProvider.cs:line 35
   --- End of inner exception stack trace ---
   at nusdm.SettingsProvider.get_Settings() in D:\nusdm-master\nusdm\nusdm\Services\SettingsProvider.cs:line 23
   at nusdm.MainWindowViewModel..ctor() in D:\nusdm-master\nusdm\nusdm\ViewModel\MainWindowViewModel.cs:line 23
   at nusdm.MainWindow..ctor() in D:\nusdm-master\nusdm\nusdm\View\MainWindow.xaml.cs:line 27
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at nusdm.App.Main()

**Comment by hexadezi** [comment]
There is a problem with the escape characters in your path. Paste your path please.

**Comment by paul23612** [comment]
Is SavePath what you are referring to?

```
{
  "CommonKey": "D7B00402659BA2ABD2CB0DB27FA2B656",
  "TitleFile": "titledb.json",
  "SavePath": "C:\Users\Paul\Desktop\dlc",
  "NintendoBaseUrl": "http://ccs.cdn.c.shop.nintendowifi.net/ccs/download/",
  "Decrypt": true,
  "DeleteAppFiles": true,
  "SkipExistingFiles": false,
  "DownloadH3Files": false,
  "MaxDegreeOfParallelism": 6
}
```

**Comment by hexadezi** [comment]
Change the line to this: "SavePath": `"C:\\Users\\Paul\\Desktop\\dlc\\",`

**Comment by paul23612** [comment]
Ok, I did that:
```
{
  "CommonKey": "D7B00402659BA2ABD2CB0DB27FA2B656",
  "TitleFile": "titledb.json",
  "SavePath": "C:\\Users\\Paul\\Desktop\\dlc\\",
  "NintendoBaseUrl": "http://ccs.cdn.c.shop.nintendowifi.net/ccs/download/",
  "Decrypt": true,
  "DeleteAppFiles": true,
  "SkipExistingFiles": false,
  "DownloadH3Files": false,
  "MaxDegreeOfParallelism": 6
}

Still same error though. Is there any possibility I need everything related to Nusdm in the same drive?
```

**Comment by hexadezi** [comment]
You need only three files:

- config.json
- nusdm.exe
- titledb.json

Does the folder dlc exist?
Did you installed these runtimes? https://versionsof.net/core/3.1/3.1.32/

**Comment by paul23612** [comment]
I have. Those folders exist, but titleb is in the Misc subfolder while the other two are together.

**Comment by paul23612** [comment]
I should also note I was only able to see the json for setting after I tried to run the exe in VS. Is that normal?

**Comment by hexadezi** [comment]
All should be in one folder. 

Did you download it here? https://github.com/hexadezi/nusdm/releases

**Comment by paul23612** [comment]
Ahhh, that was the problem. I guess the other I got wasn't meant to be used this way. Anyways, really appreciate your help sir.  Have a good day!

**Comment by hexadezi** [comment]
you too
